version: '3'

server:
  command: php public/index.php
  env:
    - APP_ENV: prod

http:
  address: 0.0.0.0:80
  middleware: [ "static", "gzip" ]
  pool:
    debug: false
  uploads:
    forbid: [ ".php", ".exe", ".bat" ]
  static:
    dir: "public"
    forbid: [ ".php", ".htaccess" ]

rpc:
  listen: tcp://127.0.0.1:6001

temporal:
  address: temporal:7233
  activities:
    num_workers: 4

logs:
  mode: production
  channels:
    http:
      level: error
    server:
      level: error
      mode: raw
    metrics:
      level: error
