<?php

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: personage_experience.proto

namespace App\Shared\GPBMetadata;

class PersonageExperience
{
    public static $is_initialized = false;

    public static function initOnce()
    {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (true == static::$is_initialized) {
            return;
        }
        $pool->internalAddGeneratedFile(
            '
b
personage_experience.prototransfer.personage"(
ExperienceTransfer

experience (bproto3', true);

        static::$is_initialized = true;
    }
}
