<?php

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: personage_stats.proto

namespace App\Shared\GPBMetadata;

class PersonageStats
{
    public static $is_initialized = false;

    public static function initOnce()
    {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (true == static::$is_initialized) {
            return;
        }
        $pool->internalAddGeneratedFile(
            '
�
personage_stats.prototransfer.personage"�

StatsTransfer
strength (
agility (
	intuition (
	endurance (

intelligence (
wisdom (

spirituality (bproto3', true);

        static::$is_initialized = true;
    }
}
