<?php

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: personage_battle_counter.proto

namespace App\Shared\GPBMetadata;

class PersonageBattleCounter
{
    public static $is_initialized = false;

    public static function initOnce()
    {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (true == static::$is_initialized) {
            return;
        }
        $pool->internalAddGeneratedFile(
            '
�
personage_battle_counter.prototransfer.personage"E
BattleCounterTransfer

wins (
defeats (
draws (bproto3', true);

        static::$is_initialized = true;
    }
}
