<?php

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: personage.proto

namespace App\Shared\GPBMetadata;

class Personage
{
    public static $is_initialized = false;

    public static function initOnce()
    {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (true == static::$is_initialized) {
            return;
        }
        PersonageGender::initOnce();
        PersonageStats::initOnce();
        PersonageBattleCounter::initOnce();
        PersonageExperience::initOnce();
        $pool->internalAddGeneratedFile(
            '
�
personage.prototransfer.personagepersonage_stats.protopersonage_battle_counter.protopersonage_experience.proto"�
PersonageTransfer
nickname (	
level (0
stats (
2!.transfer.personage.StatsTransfer:
battles (
2).transfer.personage.BattleCounterTransfer:

experience (
2&.transfer.personage.ExperienceTransferbproto3', true);

        static::$is_initialized = true;
    }
}
