<?php

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: personage_battle_counter.proto

namespace App\Shared\Transfer\Personage;

use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>transfer.personage.BattleCounterTransfer</code>.
 */
class BattleCounterTransfer extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 wins = 1;</code>.
     */
    protected $wins = 0;
    /**
     * Generated from protobuf field <code>int32 defeats = 2;</code>.
     */
    protected $defeats = 0;
    /**
     * Generated from protobuf field <code>int32 draws = 3;</code>.
     */
    protected $draws = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *                    Optional. Data for populating the Message object.
     *
     * @var int $wins
     * @var int $defeats
     * @var int $draws
     *          }
     */
    public function __construct($data = null)
    {
        \App\Shared\GPBMetadata\PersonageBattleCounter::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 wins = 1;</code>.
     *
     * @return int
     */
    public function getWins()
    {
        return $this->wins;
    }

    /**
     * Generated from protobuf field <code>int32 wins = 1;</code>.
     *
     * @param int $var
     *
     * @return $this
     */
    public function setWins($var)
    {
        GPBUtil::checkInt32($var);
        $this->wins = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 defeats = 2;</code>.
     *
     * @return int
     */
    public function getDefeats()
    {
        return $this->defeats;
    }

    /**
     * Generated from protobuf field <code>int32 defeats = 2;</code>.
     *
     * @param int $var
     *
     * @return $this
     */
    public function setDefeats($var)
    {
        GPBUtil::checkInt32($var);
        $this->defeats = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 draws = 3;</code>.
     *
     * @return int
     */
    public function getDraws()
    {
        return $this->draws;
    }

    /**
     * Generated from protobuf field <code>int32 draws = 3;</code>.
     *
     * @param int $var
     *
     * @return $this
     */
    public function setDraws($var)
    {
        GPBUtil::checkInt32($var);
        $this->draws = $var;

        return $this;
    }
}
