<?php

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: personage_experience.proto

namespace App\Shared\Transfer\Personage;

use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>transfer.personage.ExperienceTransfer</code>.
 */
class ExperienceTransfer extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 experience = 1;</code>.
     */
    protected $experience = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *                    Optional. Data for populating the Message object.
     *
     * @var int $experience
     *          }
     */
    public function __construct($data = null)
    {
        \App\Shared\GPBMetadata\PersonageExperience::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 experience = 1;</code>.
     *
     * @return int
     */
    public function getExperience()
    {
        return $this->experience;
    }

    /**
     * Generated from protobuf field <code>int32 experience = 1;</code>.
     *
     * @param int $var
     *
     * @return $this
     */
    public function setExperience($var)
    {
        GPBUtil::checkInt32($var);
        $this->experience = $var;

        return $this;
    }
}
