<?php

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: personage_registration.proto

namespace App\Shared\Transfer\Personage;

use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>transfer.personage.RegistrationTransfer</code>.
 */
class RegistrationTransfer extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string nickname = 1;</code>.
     */
    protected $nickname = '';
    /**
     * Generated from protobuf field <code>string password = 2;</code>.
     */
    protected $password = '';
    /**
     * Generated from protobuf field <code>string email = 3;</code>.
     */
    protected $email = '';
    /**
     * Generated from protobuf field <code>int32 birthdayDate = 4;</code>.
     */
    protected $birthdayDate = 0;
    /**
     * Generated from protobuf field <code>string realName = 5;</code>.
     */
    protected $realName = '';
    /**
     * Generated from protobuf field <code>string city = 6;</code>.
     */
    protected $city = '';
    /**
     * Generated from protobuf field <code>.transfer.personage.PersonageGender gender = 7;</code>.
     */
    protected $gender = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *                    Optional. Data for populating the Message object.
     *
     * @var string $nickname
     * @var string $password
     * @var string $email
     * @var int    $birthdayDate
     * @var string $realName
     * @var string $city
     * @var int    $gender
     *             }
     */
    public function __construct($data = null)
    {
        \App\Shared\GPBMetadata\PersonageRegistration::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string nickname = 1;</code>.
     *
     * @return string
     */
    public function getNickname()
    {
        return $this->nickname;
    }

    /**
     * Generated from protobuf field <code>string nickname = 1;</code>.
     *
     * @param string $var
     *
     * @return $this
     */
    public function setNickname($var)
    {
        GPBUtil::checkString($var, true);
        $this->nickname = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string password = 2;</code>.
     *
     * @return string
     */
    public function getPassword()
    {
        return $this->password;
    }

    /**
     * Generated from protobuf field <code>string password = 2;</code>.
     *
     * @param string $var
     *
     * @return $this
     */
    public function setPassword($var)
    {
        GPBUtil::checkString($var, true);
        $this->password = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string email = 3;</code>.
     *
     * @return string
     */
    public function getEmail()
    {
        return $this->email;
    }

    /**
     * Generated from protobuf field <code>string email = 3;</code>.
     *
     * @param string $var
     *
     * @return $this
     */
    public function setEmail($var)
    {
        GPBUtil::checkString($var, true);
        $this->email = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 birthdayDate = 4;</code>.
     *
     * @return int
     */
    public function getBirthdayDate()
    {
        return $this->birthdayDate;
    }

    /**
     * Generated from protobuf field <code>int32 birthdayDate = 4;</code>.
     *
     * @param int $var
     *
     * @return $this
     */
    public function setBirthdayDate($var)
    {
        GPBUtil::checkInt32($var);
        $this->birthdayDate = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string realName = 5;</code>.
     *
     * @return string
     */
    public function getRealName()
    {
        return $this->realName;
    }

    /**
     * Generated from protobuf field <code>string realName = 5;</code>.
     *
     * @param string $var
     *
     * @return $this
     */
    public function setRealName($var)
    {
        GPBUtil::checkString($var, true);
        $this->realName = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string city = 6;</code>.
     *
     * @return string
     */
    public function getCity()
    {
        return $this->city;
    }

    /**
     * Generated from protobuf field <code>string city = 6;</code>.
     *
     * @param string $var
     *
     * @return $this
     */
    public function setCity($var)
    {
        GPBUtil::checkString($var, true);
        $this->city = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.transfer.personage.PersonageGender gender = 7;</code>.
     *
     * @return int
     */
    public function getGender()
    {
        return $this->gender;
    }

    /**
     * Generated from protobuf field <code>.transfer.personage.PersonageGender gender = 7;</code>.
     *
     * @param int $var
     *
     * @return $this
     */
    public function setGender($var)
    {
        GPBUtil::checkEnum($var, PersonageGender::class);
        $this->gender = $var;

        return $this;
    }
}
