<?php

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: personage_stats.proto

namespace App\Shared\Transfer\Personage;

use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>transfer.personage.StatsTransfer</code>.
 */
class StatsTransfer extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 strength = 1;</code>.
     */
    protected $strength = 0;
    /**
     * Generated from protobuf field <code>int32 agility = 2;</code>.
     */
    protected $agility = 0;
    /**
     * Generated from protobuf field <code>int32 intuition = 3;</code>.
     */
    protected $intuition = 0;
    /**
     * Generated from protobuf field <code>int32 endurance = 4;</code>.
     */
    protected $endurance = 0;
    /**
     * Generated from protobuf field <code>int32 intelligence = 5;</code>.
     */
    protected $intelligence = 0;
    /**
     * Generated from protobuf field <code>int32 wisdom = 6;</code>.
     */
    protected $wisdom = 0;
    /**
     * Generated from protobuf field <code>int32 spirituality = 7;</code>.
     */
    protected $spirituality = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *                    Optional. Data for populating the Message object.
     *
     * @var int $strength
     * @var int $agility
     * @var int $intuition
     * @var int $endurance
     * @var int $intelligence
     * @var int $wisdom
     * @var int $spirituality
     *          }
     */
    public function __construct($data = null)
    {
        \App\Shared\GPBMetadata\PersonageStats::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 strength = 1;</code>.
     *
     * @return int
     */
    public function getStrength()
    {
        return $this->strength;
    }

    /**
     * Generated from protobuf field <code>int32 strength = 1;</code>.
     *
     * @param int $var
     *
     * @return $this
     */
    public function setStrength($var)
    {
        GPBUtil::checkInt32($var);
        $this->strength = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 agility = 2;</code>.
     *
     * @return int
     */
    public function getAgility()
    {
        return $this->agility;
    }

    /**
     * Generated from protobuf field <code>int32 agility = 2;</code>.
     *
     * @param int $var
     *
     * @return $this
     */
    public function setAgility($var)
    {
        GPBUtil::checkInt32($var);
        $this->agility = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 intuition = 3;</code>.
     *
     * @return int
     */
    public function getIntuition()
    {
        return $this->intuition;
    }

    /**
     * Generated from protobuf field <code>int32 intuition = 3;</code>.
     *
     * @param int $var
     *
     * @return $this
     */
    public function setIntuition($var)
    {
        GPBUtil::checkInt32($var);
        $this->intuition = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 endurance = 4;</code>.
     *
     * @return int
     */
    public function getEndurance()
    {
        return $this->endurance;
    }

    /**
     * Generated from protobuf field <code>int32 endurance = 4;</code>.
     *
     * @param int $var
     *
     * @return $this
     */
    public function setEndurance($var)
    {
        GPBUtil::checkInt32($var);
        $this->endurance = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 intelligence = 5;</code>.
     *
     * @return int
     */
    public function getIntelligence()
    {
        return $this->intelligence;
    }

    /**
     * Generated from protobuf field <code>int32 intelligence = 5;</code>.
     *
     * @param int $var
     *
     * @return $this
     */
    public function setIntelligence($var)
    {
        GPBUtil::checkInt32($var);
        $this->intelligence = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 wisdom = 6;</code>.
     *
     * @return int
     */
    public function getWisdom()
    {
        return $this->wisdom;
    }

    /**
     * Generated from protobuf field <code>int32 wisdom = 6;</code>.
     *
     * @param int $var
     *
     * @return $this
     */
    public function setWisdom($var)
    {
        GPBUtil::checkInt32($var);
        $this->wisdom = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 spirituality = 7;</code>.
     *
     * @return int
     */
    public function getSpirituality()
    {
        return $this->spirituality;
    }

    /**
     * Generated from protobuf field <code>int32 spirituality = 7;</code>.
     *
     * @param int $var
     *
     * @return $this
     */
    public function setSpirituality($var)
    {
        GPBUtil::checkInt32($var);
        $this->spirituality = $var;

        return $this;
    }
}
